# -*- mode: ruby -*-
# vi: set ft=ruby :

cfg = {
    :balancers => [
        {:name=>'balancer1', :ip=>'172.28.48.12', :hostport=>8080},
    ],
    :appservers => [
        {:name=>'appserver1', :ip=> '172.28.48.183'},
    ],
    :static => [
        {:name=> 'static1', :ip=> '172.28.48.26'},
    ],
}

Vagrant.configure("2") do |config|

    config.vm.box = "bento/debian-8.5"
    config.vm.box_check_update = false

    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 256]
    end

    cfg[:balancers].each do |balancer_cfg|
        config.vm.define balancer_cfg[:name] do |haproxy|
            haproxy.vm.network "forwarded_port", guest:80 , host: balancer_cfg[:hostport]
            haproxy.vm.network :private_network, ip: balancer_cfg[:ip]
        end
    end

    cfg[:appservers].each do |appserver_cfg|
        config.vm.define appserver_cfg[:name] do |tomcat|
            tomcat.vm.network :private_network, ip: appserver_cfg[:ip]
        end
    end

    cfg[:static].each do |static_cfg|
        config.vm.define static_cfg[:name] do |gatling|
            gatling.vm.network :private_network, ip: static_cfg[:ip]
        end
    end


    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
        #ansible.verbose = "vvv"

        ansible.groups = {
            'balancers' => ['balancer1'],
            'appservers' => ['appserver1'],
            'static' => ['static1'],
        }
        ansible.limit = 'all'
    end
end
