---

- name: install gatling
  apt: name=gatling state=installed # update_cache=yes

- name: configure gatling
  template: src=gatling-default dest=/etc/default/gatling

- name: assert gatling is started
  service: name=gatling state=restarted enabled=yes
